apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  labels:
    machineconfiguration.openshift.io/role: intracom
  name: intracom
spec:
  machineConfigSelector:
    matchExpressions:
    - key: machineconfiguration.openshift.io/role
      operator: In
      values:
      - worker
      - intracom
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/intracom: ""
  paused: false
